const cities=[['New York','USA','🗽'],['Los Angeles','USA','🌴'],['Chicago','USA','🌆'],['Miami','USA','🌊'],['Las Vegas','USA','🎰'],['San Francisco','USA','🌉'],['Austin','USA','🎸'],['Seattle','USA','☕'],['Boston','USA','🧭'],['Washington, DC','USA','🏛️'],['Philadelphia','USA','🔔'],['San Diego','USA','🌅'],['Denver','USA','🏔️'],['Atlanta','USA','🍑'],['Dallas','USA','⭐'],['Houston','USA','🚀'],['New Orleans','USA','🎺'],['Nashville','USA','🎸'],['Orlando','USA','🎢'],['Portland','USA','🌲'],['Phoenix','USA','🌵'],['Minneapolis','USA','🏙️'],['Detroit','USA','🎶'],['San Antonio','USA','🌮'],['Charlotte','USA','🏁'],['Tampa','USA','🌴'],['San Jose','USA','💡'],['Kansas City','USA','🎷'],['St. Louis','USA','🎵'],['Cleveland','USA','🎸'],['Toronto','Canada','🍁'],['Vancouver','Canada','🏔️'],['Montreal','Canada','🎨'],['Calgary','Canada','🤠'],['Ottawa','Canada','🍁'],['Quebec City','Canada','🏰']];
const g=document.querySelector('#cityGrid'),search=document.querySelector('#search'),grid=document.querySelector('#resultsGrid'),meta=document.querySelector('#resultMeta');let showingAll=false,current='all',last=[];
const TICKETMASTER_AFFILIATE='https://ticketmaster.evyy.net/c/7700588/264167/4272?u=';
const now=new Date(),currentYear=now.getFullYear(),currentMonth=now.toLocaleString('en-US',{month:'long'});
const popularSearches=['outdoor events','fun events','free events','today events','upcoming events','upcoming festivals','national events','events this month','events this weekend','live music','food markets','things to do'];
const seasonalSearches=[`events in ${currentMonth} ${currentYear}`,`upcoming events in ${currentYear}`,`free events in ${currentMonth} ${currentYear}`,`fun events in ${currentMonth} ${currentYear}`,`outdoor events in ${currentYear} today`,`events this month ${currentYear}`,`upcoming festivals in ${currentYear}`];
function affiliateUrl(url){if(!url)return '';try{const parsed=new URL(url);if(!/ticketmaster\./i.test(parsed.hostname))return url;return TICKETMASTER_AFFILIATE+encodeURIComponent(url)}catch{return url}}
function renderCities(){g.innerHTML='';(showingAll?cities:cities.slice(0,12)).forEach(c=>{const b=document.createElement('button');b.className='city';b.innerHTML=`<i>${c[2]}</i><b>${c[0]}</b><small>${c[1]} · Explore events →</small>`;b.onclick=()=>searchCity(c[0]);g.appendChild(b)})}
function renderPopularSearches(){let section=document.querySelector('#popularSearches');if(!section){section=document.createElement('section');section.id='popularSearches';section.className='popular-searches';g.closest('section').after(section)}const selected=cities.slice(0,12),keywords=[...popularSearches,...seasonalSearches];section.innerHTML=`<div class="head"><div><div class="eyebrow">POPULAR SEARCHES</div><h2>Explore events by city, month and year.</h2></div></div><div class="popular-search-grid">${selected.map(c=>keywords.map(k=>`<button onclick="quick('${k.replace(/'/g,"\\'")} in ${c[0]}')">${k} in <b>${c[0]}</b></button>`).join('')).join('')}</div>`}
function showAllCities(){showingAll=!showingAll;renderCities();document.querySelector('.text-button').textContent=showingAll?'Show fewer cities ↑':'View all cities →'}
function searchCity(city){search.value=`events in ${city} ${currentMonth} ${currentYear}`;go()}
function esc(v=''){return String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
function openEvent(url){if(url)window.open(affiliateUrl(url),'_blank','noopener')}
function renderResults(list){grid.innerHTML=list.map(e=>{const destination=e.url||'',outbound=affiliateUrl(destination);return `<article class="event-card${destination?' event-card-clickable':''}"${destination?` data-event-url="${esc(destination)}" role="link" tabindex="0" aria-label="Open official ticket page for ${esc(e.name)}"`:''}>${e.image?`<img src="${esc(e.image)}" alt="" loading="lazy" style="width:100%;height:150px;object-fit:cover;border-radius:14px;margin-bottom:14px">`:''}<div class="event-type">${esc(e.type).toUpperCase()}</div><h3>${esc(e.name)}</h3><p>📍 ${esc(e.city||e.venue||'Location TBA')} · 📅 ${esc(e.date||'Date TBA')}</p><b>${esc(e.price)}</b>${destination?`<a class="event-link" href="${esc(outbound)}" target="_blank" rel="sponsored noopener">Get tickets →</a>`:''}</article>`}).join('')||'<p>No events found. Try another city or search.</p>';grid.querySelectorAll('.event-card-clickable').forEach(card=>{const url=card.dataset.eventUrl;card.style.cursor='pointer';card.addEventListener('click',e=>{if(e.target.closest('a'))return;openEvent(url)});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('a')){e.preventDefault();openEvent(url)}})})}
function cityFromQuery(q){const lower=q.toLowerCase();return cities.slice().sort((a,b)=>b[0].length-a[0].length).find(c=>lower.includes(c[0].toLowerCase()))?.[0]||''}
function keywordFromQuery(q,city){if(!city)return q;return q.replace(new RegExp(city.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig'),'').replace(/\b(in|near|events?|things to do|today|tonight|this month|this weekend|upcoming|\d{4}|january|february|march|april|may|june|july|august|september|october|november|december|usa|canada)\b/gi,' ').replace(/\s+/g,' ').trim()||'events'}
function syncSearchUrl(q){
  // Keep clean SEO landing pages clean. Only normal homepage searches use ?q=.
  if(location.pathname!=='/')return;
  const u=new URL(location.href);if(q)u.searchParams.set('q',q);else u.searchParams.delete('q');history.replaceState({},'',u)
}
async function go(){const q=search.value.trim();syncSearchUrl(q);meta.textContent='Loading live events…';grid.innerHTML='<p>Finding upcoming events…</p>';document.querySelector('#results').scrollIntoView({behavior:'smooth'});try{const city=cityFromQuery(q),keyword=keywordFromQuery(q,city),p=new URLSearchParams();if(city)p.set('city',city);if(keyword)p.set('keyword',keyword);if(current!=='all'&&current!=='free')p.set('classificationName',current==='festival'?'Miscellaneous':current);const r=await fetch('https://eventstarget-api.onrender.com/api/events?'+p.toString()),data=await r.json();if(!r.ok)throw new Error(data.error||'Event service unavailable');last=data.events||[];if(current==='free')last=last.filter(e=>/free|\$\s*0(?:\.00)?/i.test(e.price));meta.textContent=`${last.length} live event${last.length===1?'':'s'} found${q?` for “${q}”`:''}`;renderResults(last)}catch(e){meta.textContent='Live event search is being configured';grid.innerHTML='<p>Live event data will appear once the secure API key is added to Render.</p>'}}
function quick(q){search.value=q;go()}
function filterEvents(type){current=type;document.querySelectorAll('.filters button').forEach(b=>b.classList.toggle('active',b.textContent.toLowerCase().startsWith(type==='all'?'all':type)));go()}
function openM(t,p){document.querySelector('#mt').textContent=t;document.querySelector('#mp').textContent=p;document.querySelector('#modal').classList.add('show')}
function closeM(){document.querySelector('#modal').classList.remove('show')}
function focusSearch(){search.focus();window.scrollTo({top:0,behavior:'smooth'})}
search.addEventListener('keydown',e=>{if(e.key==='Enter')go()});document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeM()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeM()});const ideas=['Find a local outdoor movie, market, museum day or community festival.','Build a last-minute plan around live music, food and a new neighborhood.','Pick one new city activity you have never tried before.'];let n=0;function shuffle(){n=(n+1)%ideas.length;document.querySelector('#idea').textContent=ideas[n]}renderCities();renderPopularSearches();grid.innerHTML='<p>Search above to discover live events.</p>';const initialQuery=new URLSearchParams(location.search).get('q');if(initialQuery){search.value=initialQuery;go()}